"""Report builder — assembles audit findings into an LLM-optimized markdown report."""

from __future__ import annotations

import json
import logging
from collections import defaultdict
from datetime import datetime
from typing import Any

from .config import Config
from .diff_report import ReportDiff
from .findings import (
    AuditData,
    ChangeSummary,
    Finding,
    ResearchResult,
    Severity,
    deduplicate,
)
from .utils import estimate_tokens

log = logging.getLogger("audit")

# Max findings shown in detail per tool/category (keeps report compact)
MAX_DETAIL_PER_TOOL = 20
MAX_DETAIL_PER_PATTERN_CAT = 15


class ReportBuilder:
    """Builds a condensed markdown report optimized for LLM consumption."""

    def __init__(self, config: Config):
        self.config = config
        self.include_json = config.get("report", "include_json_blocks", default=True)
        self.include_tokens = config.get("report", "include_token_estimate", default=True)

    def build(
        self,
        findings: list[Finding],
        tier1_summary: dict,
        change_summary: ChangeSummary | None,
        audit_data: AuditData | None,
        research_results: list[ResearchResult] | None,
        tiers_run: list[int],
        duration: float,
        diff: ReportDiff | None = None,
        trend_report: Any = None,
    ) -> str:
        """Build the full report and write to file. Returns the report text."""
        deduped = deduplicate(findings)
        sections: list[str] = []

        # Header
        sections.append(f"# Automated Audit Report: {self.config.project_name}")
        sections.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        sections.append(f"**Tiers run:** {tiers_run}")
        sections.append("")

        # Executive Summary
        sections.append(self._build_summary(deduped, tier1_summary, audit_data, tiers_run, duration))

        # Differential report section (if available)
        if diff is not None:
            sections.append(self._build_diff_section(diff))

        # Trend section (if available)
        if trend_report is not None:
            sections.append(self._build_trend_section(trend_report))

        # Tier 1: Build & Static Analysis
        if 1 in tiers_run:
            sections.append(self._build_tier1_section(deduped, tier1_summary))

        # Tier 2: Pattern Scan
        if 2 in tiers_run:
            sections.append(self._build_tier2_section(deduped))

        # Tier 3: Changed Files
        if 3 in tiers_run and change_summary:
            sections.append(self._build_tier3_section(change_summary, deduped))

        # Tier 4: Statistics
        if 4 in tiers_run and audit_data:
            sections.append(self._build_tier4_section(audit_data))

        # Tier 5: Research
        if 5 in tiers_run and research_results:
            sections.append(self._build_tier5_section(research_results))

        report = "\n".join(sections)

        # Token estimate footer
        if self.include_tokens:
            tokens = estimate_tokens(report)
            report += f"\n\n---\n*Generated by audit.py | Estimated tokens: ~{tokens:,}*\n"

        # Write report with date-time in filename
        base_path = self.config.report_path
        base_dir = base_path.parent
        base_dir.mkdir(parents=True, exist_ok=True)

        timestamp = datetime.now().strftime("%Y-%m-%d_%H%M%S")
        stem = base_path.stem  # e.g. "AUTOMATED_AUDIT_REPORT"
        output_path = base_dir / f"{stem}_{timestamp}{base_path.suffix}"
        output_path.write_text(report)

        # Also write to the stable base name so web UI /api/report has a fixed path
        base_path.write_text(report)

        # Write JSON sidecar with deduplicated findings for differential reporting
        sidecar_name = f"{stem}_{timestamp}_results.json"
        sidecar_path = base_dir / sidecar_name
        sidecar_data = [f.to_dict() for f in deduped]
        sidecar_path.write_text(json.dumps(sidecar_data, indent=2))
        log.info("JSON sidecar written to %s (%d findings)", sidecar_path, len(sidecar_data))

        log.info("Report written to %s (%d chars, ~%d tokens)",
                 output_path, len(report), estimate_tokens(report))
        log.info("Latest copy: %s", base_path)

        return report

    def _build_diff_section(self, diff: ReportDiff) -> str:
        """Build the differential comparison section."""
        lines = ["## Differential Report", ""]

        if diff.previous_path:
            lines.append(f"**Compared against:** `{diff.previous_path}`")
            lines.append("")

        lines.append(f"- **New findings:** {len(diff.new_findings)}")
        lines.append(f"- **Resolved findings:** {len(diff.resolved_findings)}")
        lines.append(f"- **Persistent findings:** {diff.persistent_count}")
        lines.append("")

        # List new HIGH+ findings in detail
        high_or_above = [
            f for f in diff.new_findings
            if f.get("severity", "info") in ("critical", "high")
        ]
        if high_or_above:
            lines.append("### New HIGH+ Findings")
            lines.append("")
            lines.append("| Severity | File | Line | Issue |")
            lines.append("|----------|------|------|-------|")
            for f in high_or_above:
                title = f.get("title", "").replace("|", "/")[:100]
                lines.append(
                    f"| {f.get('severity', '?').upper()} "
                    f"| `{f.get('file', '')}` "
                    f"| {f.get('line', '-')} "
                    f"| {title} |"
                )
            lines.append("")
        elif diff.new_findings:
            lines.append("No new HIGH or CRITICAL findings (all new findings are MEDIUM or below).")
            lines.append("")
        else:
            lines.append("No new findings since the previous audit.")
            lines.append("")

        return "\n".join(lines)

    def _build_summary(
        self,
        findings: list[Finding],
        tier1_summary: dict,
        audit_data: AuditData | None,
        tiers_run: list[int],
        duration: float,
    ) -> str:
        """Build the executive summary with JSON block."""
        counts = defaultdict(int)
        for f in findings:
            counts[f.severity.name.lower()] += 1

        build_info = tier1_summary.get("build", {})
        test_info = tier1_summary.get("tests", {})

        summary_data = {
            "findings": {
                "critical": counts.get("critical", 0),
                "high": counts.get("high", 0),
                "medium": counts.get("medium", 0),
                "low": counts.get("low", 0),
                "info": counts.get("info", 0),
                "total": len(findings),
            },
            "build": {
                "ok": build_info.get("build_ok", None),
                "warnings": build_info.get("warnings", 0),
                "errors": build_info.get("errors", 0),
            },
            "tests": {
                "passed": test_info.get("passed", 0),
                "failed": test_info.get("failed", 0),
                "skipped": test_info.get("skipped", 0),
            },
        }

        if audit_data:
            summary_data["codebase"] = {
                "total_loc": audit_data.total_loc,
                "file_count": audit_data.file_count,
            }

        summary_data["duration_seconds"] = round(duration, 1)

        lines = ["## Executive Summary", ""]
        lines.append("```json")
        lines.append(json.dumps(summary_data, indent=2))
        lines.append("```")
        lines.append("")
        return "\n".join(lines)

    def _build_tier1_section(self, findings: list[Finding], tier1_summary: dict) -> str:
        """Build Tier 1 section — compact tables, not JSON dumps."""
        lines = ["## Tier 1: Build & Static Analysis", ""]

        # Build status
        build = tier1_summary.get("build", {})
        if build.get("build_ok"):
            lines.append(f"**Build:** Clean ({build.get('warnings', 0)} warnings)")
        elif build.get("build_ok") is not None:
            lines.append(f"**Build:** FAILED ({build.get('errors', 0)} errors, "
                         f"{build.get('warnings', 0)} warnings)")
        lines.append("")

        # Tests
        tests = tier1_summary.get("tests", {})
        if tests:
            lines.append(f"**Tests:** {tests.get('passed', 0)} passed, "
                         f"{tests.get('failed', 0)} failed, "
                         f"{tests.get('skipped', 0)} skipped")
            lines.append("")

        # cppcheck — show severity breakdown + only HIGH+ in detail
        cppcheck_findings = [f for f in findings if f.category == "cppcheck"]
        if cppcheck_findings:
            lines.append(self._compact_findings_section(
                "cppcheck", cppcheck_findings, MAX_DETAIL_PER_TOOL))

        # clang-tidy — same treatment
        ct_findings = [f for f in findings if f.category == "clang_tidy"]
        if ct_findings:
            lines.append(self._compact_findings_section(
                "clang-tidy", ct_findings, MAX_DETAIL_PER_TOOL))

        return "\n".join(lines)

    def _compact_findings_section(
        self, tool_name: str, findings: list[Finding], max_detail: int
    ) -> str:
        """Render a tool's findings as severity summary + table of top issues."""
        lines: list[str] = []

        # Severity breakdown
        by_sev: dict[str, int] = defaultdict(int)
        for f in findings:
            by_sev[f.severity.name.lower()] += 1
        sev_str = ", ".join(f"{c} {s}" for s, c in sorted(by_sev.items(),
                            key=lambda x: Severity.from_string(x[0])))

        lines.append(f"### {tool_name} ({len(findings)} findings: {sev_str})")
        lines.append("")

        # Show only HIGH+ findings in detail, then count the rest
        important = [f for f in findings if f.severity <= Severity.HIGH]
        rest_count = len(findings) - len(important)

        shown = important[:max_detail]
        if shown:
            lines.append("| Severity | File | Line | Issue |")
            lines.append("|----------|------|------|-------|")
            for f in shown:
                title = f.title.replace("|", "/")[:100]
                lines.append(f"| {f.severity.name} | `{f.file}` | {f.line or '-'} | {title} |")
            if len(important) > max_detail:
                lines.append(f"| ... | | | *({len(important) - max_detail} more HIGH+ findings)* |")
        else:
            lines.append("No HIGH or CRITICAL findings.")

        if rest_count > 0:
            lines.append(f"\n*{rest_count} additional MEDIUM/LOW/INFO findings omitted "
                         f"(run with `--json` for full details).*")
        lines.append("")
        return "\n".join(lines)

    def _build_tier2_section(self, findings: list[Finding]) -> str:
        """Build Tier 2 pattern scan section — compact tables."""
        tier2 = [f for f in findings if f.source_tier == 2]
        if not tier2:
            return "## Tier 2: Pattern Scan\n\nNo pattern matches found.\n"

        lines = [f"## Tier 2: Pattern Scan ({len(tier2)} matches)", ""]

        # Group by category
        by_cat: dict[str, list[Finding]] = defaultdict(list)
        for f in tier2:
            by_cat[f.category].append(f)

        for cat, cat_findings in sorted(by_cat.items()):
            # Show count by pattern name (compact summary)
            by_pattern: dict[str, int] = defaultdict(int)
            for f in cat_findings:
                by_pattern[f.pattern_name] += 1

            lines.append(f"### {cat.replace('_', ' ').title()} ({len(cat_findings)} matches)")
            lines.append("")

            # Pattern summary line
            pat_summary = ", ".join(f"{name}: {count}" for name, count
                                    in sorted(by_pattern.items(), key=lambda x: -x[1]))
            lines.append(f"**By pattern:** {pat_summary}")
            lines.append("")

            # Show only HIGH+ in table, or first N if all same severity
            important = [f for f in cat_findings if f.severity <= Severity.HIGH]
            to_show = important[:MAX_DETAIL_PER_PATTERN_CAT] if important else cat_findings[:5]

            if to_show:
                lines.append("| File | Line | Pattern | Match |")
                lines.append("|------|------|---------|-------|")
                for f in to_show:
                    detail = f.detail.replace("|", "\\|").replace("\n", " ")[:60]
                    lines.append(f"| `{f.file}` | {f.line} | {f.pattern_name} | `{detail}` |")

                remaining = len(cat_findings) - len(to_show)
                if remaining > 0:
                    lines.append(f"| ... | | | *({remaining} more)* |")
            lines.append("")

        return "\n".join(lines)

    def _build_tier3_section(self, cs: ChangeSummary, findings: list[Finding] | None = None) -> str:
        """Build Tier 3 changed files section with diff security findings."""
        if not cs.changed_files:
            return "## Tier 3: Changed Files\n\nNo changes detected.\n"

        lines = [f"## Tier 3: Changed Files ({len(cs.changed_files)} files, "
                 f"+{cs.total_added}/-{cs.total_removed} lines)", ""]

        lines.append(f"**Subsystems touched:** {', '.join(cs.subsystems_touched)}")
        lines.append("")

        lines.append("| File | Status | +/- | Functions Changed |")
        lines.append("|------|--------|-----|-------------------|")
        for f in cs.changed_files:
            funcs = f.get("changed_functions", [])
            func_str = ", ".join(funcs[:5])
            if len(funcs) > 5:
                func_str += f" (+{len(funcs)-5} more)"
            lines.append(f"| `{f['file']}` | {f['status']} | "
                         f"+{f.get('added', 0)}/-{f.get('removed', 0)} | {func_str} |")
        lines.append("")

        # Diff security findings
        if findings:
            diff_sec = [f for f in findings if f.category == "diff_security"]
            if diff_sec:
                lines.append(f"### Diff Security Scan ({len(diff_sec)} findings in new code)")
                lines.append("")
                lines.append("| Severity | File | Line | Issue |")
                lines.append("|----------|------|------|-------|")
                for f in diff_sec[:20]:
                    title = f.title.replace("|", "/")[:100]
                    lines.append(f"| {f.severity.name} | `{f.file}` | "
                                 f"{f.line or '-'} | {title} |")
                if len(diff_sec) > 20:
                    lines.append(f"| ... | | | *({len(diff_sec) - 20} more)* |")
                lines.append("")

        return "\n".join(lines)

    def _build_tier4_section(self, data: AuditData) -> str:
        """Build Tier 4 statistics section — compact."""
        lines = [f"## Tier 4: Codebase Statistics ({data.total_loc:,} LOC, "
                 f"{data.file_count} files)", ""]

        # LOC by subsystem — single JSON block (small)
        lines.append("### LOC by Subsystem")
        lines.append("```json")
        lines.append(json.dumps(data.loc_by_subsystem, indent=2))
        lines.append("```")
        lines.append("")

        # GPU Resource Classes — only show incomplete ones
        if data.gpu_resource_classes:
            incomplete = [c for c in data.gpu_resource_classes if c["status"] != "OK"]
            lines.append(f"### GPU Resource Classes — Rule of Five "
                         f"({len(data.gpu_resource_classes)} total, "
                         f"{len(incomplete)} incomplete)")
            if incomplete:
                lines.append("")
                lines.append("| Class | File | Destructor | Move Ctor | Move Assign | Status |")
                lines.append("|-------|------|------------|-----------|-------------|--------|")
                for c in incomplete:
                    lines.append(f"| {c['class']} | `{c['file']}` | "
                                 f"{'Y' if c['destructor'] else 'N'} | "
                                 f"{'Y' if c['move_ctor'] else 'N'} | "
                                 f"{'Y' if c['move_assign'] else 'N'} | "
                                 f"{c['status']} |")
            else:
                lines.append("All GPU resource classes pass Rule of Five.")
            lines.append("")

        # Event Lifecycle — only show leaks
        if data.event_lifecycle:
            leaks = [e for e in data.event_lifecycle if e["status"] != "OK"]
            if leaks:
                lines.append(f"### Event Lifecycle Issues ({len(leaks)} possible leaks)")
                for e in leaks:
                    lines.append(f"- `{e['file']}`: {e['subscribes']} subscribes, "
                                 f"{e['unsubscribes']} unsubscribes")
                lines.append("")

        # Deferred Work Markers
        if data.deferred_by_subsystem:
            total = sum(data.deferred_by_subsystem.values())
            lines.append(f"### Deferred Work Markers ({total} total)")
            lines.append("```json")
            lines.append(json.dumps(data.deferred_by_subsystem, indent=2))
            lines.append("```")
            lines.append("")

        # Large files — top 10 only
        if data.large_files:
            threshold = self.config.get("tier4", "complexity_threshold", default=500)
            lines.append(f"### Large Files (>{threshold} lines, top 10)")
            for lf in data.large_files[:10]:
                lines.append(f"- `{lf['file']}`: {lf['lines']:,} lines")
            if len(data.large_files) > 10:
                lines.append(f"- *({len(data.large_files) - 10} more)*")
            lines.append("")

        # Uniform-Shader Sync
        us = data.uniform_sync
        if us:
            dns = us.get("declared_not_set", [])
            snd = us.get("set_not_declared", [])
            if dns or snd:
                lines.append(f"### Uniform-Shader Sync ({len(dns)} declared-not-set, "
                             f"{len(snd)} set-not-declared)")
                if dns:
                    lines.append("\n**Declared in GLSL but never set from C++:**")
                    for u in dns[:15]:
                        lines.append(f"- `{u['uniform']}` in `{u['shader']}`")
                if snd:
                    lines.append("\n**Set from C++ but not declared in any shader:**")
                    for u in snd[:15]:
                        lines.append(f"- `{u['uniform']}` in `{u['cpp_file']}`")
                lines.append("")
            else:
                lines.append(f"### Uniform-Shader Sync ({us.get('total_shader_uniforms', 0)} "
                             f"shader, {us.get('total_cpp_uniforms', 0)} C++) — all synced")
                lines.append("")

        # Include Analysis
        ia = data.include_analysis
        if ia:
            heavy = ia.get("heavy_headers", [])
            fwd = ia.get("forward_decl_candidates", [])
            circ = ia.get("circular_pairs", [])
            if heavy or fwd or circ:
                lines.append(f"### Include Analysis ({len(heavy)} heavy headers, "
                             f"{len(fwd)} forward-decl candidates, {len(circ)} circular)")
                if heavy:
                    lines.append("\n**Heavy headers (most includes):**")
                    for h in heavy[:10]:
                        lines.append(f"- `{h['file']}`: {h['includes']} includes")
                if fwd:
                    lines.append("\n**Forward declaration candidates:**")
                    for f in fwd[:10]:
                        lines.append(f"- `{f['file']}` includes `{f['includes']}` "
                                     f"but only uses `{f['class']}` as ptr/ref")
                if circ:
                    lines.append("\n**Circular includes:**")
                    for a, b in circ[:5]:
                        lines.append(f"- `{a}` <-> `{b}`")
                lines.append("")

        # Complexity
        cx = data.complexity
        if cx and cx.get("hotspots"):
            lines.append(f"### Complexity (avg CC={cx['avg_complexity']}, "
                         f"max CC={cx['max_complexity']}, "
                         f"{cx['functions_analyzed']} functions)")
            lines.append("")
            lines.append("| Function | File | Line | CC |")
            lines.append("|----------|------|------|----|")
            for h in cx["hotspots"][:10]:
                lines.append(f"| `{h['name']}` | `{h['file']}` | {h['line']} | {h['complexity']} |")
            if len(cx["hotspots"]) > 10:
                lines.append(f"| ... | | | *({len(cx['hotspots']) - 10} more)* |")
            lines.append("")

        # Dead Code
        dc = data.dead_code
        if dc:
            unused_funcs = dc.get("unused_functions", [])
            unused_incs = dc.get("unused_includes", [])
            if unused_funcs or unused_incs:
                lines.append(f"### Dead Code ({len(unused_funcs)} unused functions, "
                             f"{len(unused_incs)} unused includes)")
                lines.append("")
                if unused_funcs:
                    lines.append("**Unused functions:**")
                    lines.append("")
                    lines.append("| Function | File | Line | Reason |")
                    lines.append("|----------|------|------|--------|")
                    for uf in unused_funcs[:15]:
                        lines.append(f"| `{uf['name']}()` | `{uf['file']}` | "
                                     f"{uf['line']} | {uf['reason']} |")
                    if len(unused_funcs) > 15:
                        lines.append(f"| ... | | | *({len(unused_funcs) - 15} more)* |")
                    lines.append("")
                if unused_incs:
                    lines.append("**Unused includes:**")
                    lines.append("")
                    lines.append("| File | Line | Include |")
                    lines.append("|------|------|---------|")
                    for ui in unused_incs[:15]:
                        lines.append(f"| `{ui['file']}` | {ui['line']} | "
                                     f"`{ui['include']}` |")
                    if len(unused_incs) > 15:
                        lines.append(f"| ... | | *({len(unused_incs) - 15} more)* |")
                    lines.append("")

        # Build System Audit
        ba = data.build_audit
        if ba:
            sec_flags = ba.get("security_flags", [])
            warn_flags = ba.get("warning_flags", [])
            best_practices = ba.get("best_practices", [])
            missing_sec = [f for f in sec_flags if f["status"] == "missing"]
            missing_warn = [f for f in warn_flags if f["status"] == "missing"]
            missing_bp = [f for f in best_practices if f["status"] == "missing"]

            if missing_sec or missing_warn or missing_bp:
                lines.append(f"### Build System Audit ({len(missing_sec)} missing security flags, "
                             f"{len(missing_warn)} missing warning flags, "
                             f"{len(missing_bp)} missing best practices)")
                lines.append("")
                if missing_sec:
                    lines.append("**Missing security hardening flags:**")
                    lines.append("")
                    lines.append("| Flag | Description | CWE |")
                    lines.append("|------|-------------|-----|")
                    for f in missing_sec:
                        lines.append(f"| `{f['flag']}` | {f['description']} | "
                                     f"{f.get('cwe', '')} |")
                    lines.append("")
                if missing_warn:
                    lines.append("**Missing warning flags:**")
                    lines.append("")
                    for f in missing_warn:
                        lines.append(f"- `{f['flag']}`: {f['description']}")
                    lines.append("")
                if missing_bp:
                    lines.append("**Missing CMake best practices:**")
                    lines.append("")
                    for f in missing_bp:
                        lines.append(f"- `{f['check']}`: {f['description']}")
                    lines.append("")
            else:
                lines.append(f"### Build System Audit — all checks pass "
                             f"({len(sec_flags)} security, {len(warn_flags)} warning, "
                             f"{len(best_practices)} best practices)")
                lines.append("")

        # Code Duplication
        dup = data.duplication
        if dup:
            clone_pairs = dup.get("clone_pairs", [])
            dup_pct = dup.get("duplication_pct", 0)
            dup_lines = dup.get("duplicated_lines", 0)
            if clone_pairs:
                lines.append(f"### Code Duplication ({len(clone_pairs)} clone pairs, "
                             f"{dup_lines:,} duplicated lines, {dup_pct}%)")
                lines.append("")
                lines.append("| File A | Lines A | File B | Lines B | Lines | Type |")
                lines.append("|--------|---------|--------|---------|-------|------|")
                for cp in clone_pairs[:15]:
                    lines.append(
                        f"| `{cp['file_a']}` | {cp['start_a']}-{cp['end_a']} "
                        f"| `{cp['file_b']}` | {cp['start_b']}-{cp['end_b']} "
                        f"| {cp['lines']} | Type-{cp['clone_type']} |")
                if len(clone_pairs) > 15:
                    lines.append(f"| ... | | | | | *({len(clone_pairs) - 15} more)* |")
                lines.append("")
            else:
                lines.append(f"### Code Duplication — no significant clones detected "
                             f"({dup.get('files_scanned', 0)} files scanned)")
                lines.append("")

        # Refactoring Opportunities
        ref = data.refactoring
        if ref:
            total = ref.get("total_smells", 0)
            if total > 0:
                lines.append(f"### Refactoring Opportunities ({total} code smells)")
                lines.append("")
                lpl = ref.get("long_param_lists", [])
                if lpl:
                    lines.append(f"**Long parameter lists ({len(lpl)}):**")
                    lines.append("")
                    for item in lpl[:10]:
                        lines.append(f"- `{item['name']}()` in `{item['file']}` "
                                     f"line {item['line']}: {item['params']} params")
                    if len(lpl) > 10:
                        lines.append(f"- *({len(lpl) - 10} more)*")
                    lines.append("")
                gf = ref.get("god_files", [])
                if gf:
                    lines.append(f"**God files ({len(gf)}):**")
                    lines.append("")
                    for item in gf[:10]:
                        lines.append(f"- `{item['file']}`: {item['functions']} functions")
                    if len(gf) > 10:
                        lines.append(f"- *({len(gf) - 10} more)*")
                    lines.append("")
                lsc = ref.get("large_switch_chains", [])
                if lsc:
                    lines.append(f"**Large switch/if-else chains ({len(lsc)}):**")
                    lines.append("")
                    for item in lsc[:10]:
                        lines.append(f"- `{item['file']}` line {item['line']}: "
                                     f"{item['count']} {item['type']}")
                    if len(lsc) > 10:
                        lines.append(f"- *({len(lsc) - 10} more)*")
                    lines.append("")
                dn = ref.get("deep_nesting", [])
                if dn:
                    lines.append(f"**Deep nesting ({len(dn)}):**")
                    lines.append("")
                    for item in dn[:10]:
                        lines.append(f"- `{item['name']}()` in `{item['file']}` "
                                     f"line {item['line']}: depth {item['depth']}")
                    if len(dn) > 10:
                        lines.append(f"- *({len(dn) - 10} more)*")
                    lines.append("")
                ss = ref.get("similar_signatures", [])
                if ss:
                    lines.append(f"**Similar function signatures ({len(ss)}):**")
                    lines.append("")
                    for item in ss[:10]:
                        lines.append(f"- `{item['name_a']}()` and `{item['name_b']}()` "
                                     f"share params `({item['param_types']})`")
                    if len(ss) > 10:
                        lines.append(f"- *({len(ss) - 10} more)*")
                    lines.append("")

        return "\n".join(lines)

    def _build_trend_section(self, trend_report: Any) -> str:
        """Build the finding trend section from a TrendReport."""
        lines = ["## Finding Trends", ""]

        direction = trend_report.direction
        delta = trend_report.finding_delta
        delta_str = f"+{delta}" if delta > 0 else str(delta)

        lines.append(f"**Overall trend:** {direction} ({delta_str} findings)")
        lines.append("")

        categories = trend_report.categories
        if categories:
            # Group categories by direction
            improving = [c for c, d in categories.items() if d == "improving"]
            worsening = [c for c, d in categories.items() if d == "worsening"]
            stable = [c for c, d in categories.items() if d == "stable"]

            if improving:
                lines.append(f"**Improving:** {', '.join(improving)}")
            if worsening:
                lines.append(f"**Worsening:** {', '.join(worsening)}")
            if stable:
                lines.append(f"**Stable:** {', '.join(stable)}")
            lines.append("")

        return "\n".join(lines)

    def _build_tier5_section(self, results: list[ResearchResult]) -> str:
        """Build Tier 5 research section."""
        if not results:
            return "## Tier 5: Online Research\n\nNo research performed.\n"

        # Separate improvement queries from general/CVE queries
        improvement_keywords = ("improvements", "best practices", "techniques",
                                "alternatives", "optimization", "latest", "modern")
        improvements = [r for r in results if r.results and not r.error
                        and any(kw in r.query.lower() for kw in improvement_keywords)]
        security = [r for r in results if r.results and not r.error
                    and r not in improvements]
        errors = [r for r in results if r.error]
        valid = [r for r in results if r.results and not r.error]

        lines = [f"## Tier 5: Online Research ({len(valid)}/{len(results)} queries returned results)", ""]

        # Improvement research first (most actionable)
        if improvements:
            lines.append(f"### Improvement Opportunities ({len(improvements)} topics)")
            lines.append("")
            for r in improvements:
                cached_tag = " (cached)" if r.cached else ""
                lines.append(f"**{r.query}**{cached_tag}")
                for item in r.results[:2]:
                    title = item.get("title", "")
                    url = item.get("url", "")
                    snippet = item.get("snippet", "")[:150]
                    lines.append(f"- [{title}]({url})")
                    if snippet:
                        lines.append(f"  > {snippet}")
                lines.append("")

        # Security / CVE research
        if security:
            lines.append(f"### Security & CVE Research ({len(security)} topics)")
            lines.append("")

        for r in security:
            cached_tag = " (cached)" if r.cached else ""
            lines.append(f"### {r.query}{cached_tag}")
            for item in r.results:
                title = item.get("title", "")
                url = item.get("url", "")
                snippet = item.get("snippet", "")[:150]
                lines.append(f"- **{title}**")
                if url:
                    lines.append(f"  {url}")
                if snippet:
                    lines.append(f"  > {snippet}")
            lines.append("")

        if errors:
            lines.append("### Research Errors")
            for r in errors:
                lines.append(f"- {r.query}: {r.error}")
            lines.append("")

        return "\n".join(lines)
